/**
 * Excerpt Generator Utility
 * 
 * Provides functions for automatically generating excerpts from blog post content.
 * Strips markdown formatting and truncates to a specified character limit.
 */

/**
 * Default character limit for auto-generated excerpts
 */
export const DEFAULT_EXCERPT_LENGTH = 200;

/**
 * Strip markdown formatting from text
 * 
 * Removes:
 * - Headers (# ## ###)
 * - Bold (**text** or __text__)
 * - Italic (*text* or _text_)
 * - Links ([text](url))
 * - Images (![alt](url))
 * - Code blocks (```code```)
 * - Inline code (`code`)
 * - Blockquotes (> text)
 * - Lists (- item or * item or 1. item)
 * - Horizontal rules (--- or ***)
 * - HTML tags
 * 
 * @param markdown - Markdown text to strip
 * @returns Plain text without markdown formatting
 */
export function stripMarkdown(markdown: string): string {
  let text = markdown;

  // Remove code blocks (```...```)
  text = text.replace(/```[\s\S]*?```/g, '');

  // Remove inline code (`...`)
  text = text.replace(/`([^`]+)`/g, '$1');

  // Remove images (![alt](url))
  text = text.replace(/!\[([^\]]*)\]\([^)]+\)/g, '');

  // Remove links but keep text ([text](url))
  text = text.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');

  // Remove headers (# ## ###)
  text = text.replace(/^#{1,6}\s+/gm, '');

  // Remove bold (**text** or __text__)
  text = text.replace(/(\*\*|__)(.*?)\1/g, '$2');

  // Remove italic (*text* or _text_)
  text = text.replace(/(\*|_)(.*?)\1/g, '$2');

  // Remove blockquotes (> text)
  text = text.replace(/^>\s+/gm, '');

  // Remove unordered list markers (- or * or +)
  text = text.replace(/^[\s]*[-*+]\s+/gm, '');

  // Remove ordered list markers (1. 2. 3.)
  text = text.replace(/^[\s]*\d+\.\s+/gm, '');

  // Remove horizontal rules (--- or ***)
  text = text.replace(/^[\s]*[-*_]{3,}[\s]*$/gm, '');

  // Remove HTML tags
  text = text.replace(/<[^>]+>/g, '');

  // Remove extra whitespace and newlines
  text = text.replace(/\n\s*\n/g, '\n'); // Multiple newlines to single
  text = text.replace(/\n/g, ' '); // Newlines to spaces
  text = text.replace(/\s+/g, ' '); // Multiple spaces to single

  // Trim whitespace
  text = text.trim();

  return text;
}

/**
 * Generate excerpt from content
 * 
 * Extracts the first N characters from the content after stripping markdown.
 * Ensures the excerpt ends at a word boundary and adds ellipsis if truncated.
 * 
 * @param content - Blog post content (markdown)
 * @param maxLength - Maximum character length (default: 200)
 * @returns Generated excerpt
 */
export function generateExcerpt(
  content: string,
  maxLength: number = DEFAULT_EXCERPT_LENGTH,
): string {
  if (!content || content.trim().length === 0) {
    return '';
  }

  // Strip markdown formatting
  const plainText = stripMarkdown(content);

  // If content is shorter than max length, return as is
  if (plainText.length <= maxLength) {
    return plainText;
  }

  // Truncate to max length
  let excerpt = plainText.substring(0, maxLength);

  // Find the last space to avoid cutting words
  const lastSpaceIndex = excerpt.lastIndexOf(' ');

  if (lastSpaceIndex > 0) {
    excerpt = excerpt.substring(0, lastSpaceIndex);
  }

  // Add ellipsis
  excerpt = excerpt.trim() + '...';

  return excerpt;
}

/**
 * Validate excerpt length
 * 
 * Checks if an excerpt is within acceptable length limits.
 * 
 * @param excerpt - Excerpt to validate
 * @param maxLength - Maximum allowed length (default: 500)
 * @returns True if valid, false otherwise
 */
export function isValidExcerptLength(
  excerpt: string,
  maxLength: number = 500,
): boolean {
  return excerpt.length <= maxLength;
}

/**
 * Get excerpt preview
 * 
 * Returns a preview of what the auto-generated excerpt would look like
 * without actually modifying the content.
 * 
 * @param content - Blog post content
 * @param maxLength - Maximum character length
 * @returns Preview of auto-generated excerpt
 */
export function getExcerptPreview(
  content: string,
  maxLength: number = DEFAULT_EXCERPT_LENGTH,
): {
  excerpt: string;
  isAutoGenerated: boolean;
  characterCount: number;
} {
  const excerpt = generateExcerpt(content, maxLength);

  return {
    excerpt,
    isAutoGenerated: true,
    characterCount: excerpt.length,
  };
}
