import {
  stripMarkdown,
  generateExcerpt,
  isValidExcerptLength,
  getExcerptPreview,
  DEFAULT_EXCERPT_LENGTH,
} from '../excerpt-utils';

describe('Excerpt Utils', () => {
  describe('stripMarkdown', () => {
    it('should remove headers', () => {
      const markdown = '# Header 1\n## Header 2\n### Header 3';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Header 1 Header 2 Header 3');
    });

    it('should remove bold formatting', () => {
      const markdown = '**bold text** and __more bold__';
      const result = stripMarkdown(markdown);
      expect(result).toBe('bold text and more bold');
    });

    it('should remove italic formatting', () => {
      const markdown = '*italic text* and _more italic_';
      const result = stripMarkdown(markdown);
      expect(result).toBe('italic text and more italic');
    });

    it('should remove links but keep text', () => {
      const markdown = 'Check out [this link](https://example.com)';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Check out this link');
    });

    it('should remove images', () => {
      const markdown = 'Here is an image: ![alt text](image.jpg)';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Here is an image:');
    });

    it('should remove code blocks', () => {
      const markdown = 'Some text\n```javascript\nconst x = 1;\n```\nMore text';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Some text More text');
    });

    it('should remove inline code', () => {
      const markdown = 'Use `console.log()` to debug';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Use console.log() to debug');
    });

    it('should remove blockquotes', () => {
      const markdown = '> This is a quote\n> Another line';
      const result = stripMarkdown(markdown);
      expect(result).toBe('This is a quote Another line');
    });

    it('should remove list markers', () => {
      const markdown = '- Item 1\n* Item 2\n+ Item 3\n1. Item 4';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Item 1 Item 2 Item 3 Item 4');
    });

    it('should remove HTML tags', () => {
      const markdown = 'Some <strong>HTML</strong> content';
      const result = stripMarkdown(markdown);
      expect(result).toBe('Some HTML content');
    });
  });

  describe('generateExcerpt', () => {
    it('should return empty string for empty content', () => {
      expect(generateExcerpt('')).toBe('');
      expect(generateExcerpt('   ')).toBe('');
    });

    it('should return full text if shorter than max length', () => {
      const content = 'Short content';
      const result = generateExcerpt(content, 100);
      expect(result).toBe('Short content');
    });

    it('should truncate long content', () => {
      const content = 'This is a very long piece of content that should be truncated to fit within the maximum length limit specified for the excerpt generation function.';
      const result = generateExcerpt(content, 50);
      expect(result.length).toBeLessThanOrEqual(54); // 50 + '...'
      expect(result).toContain('...');
    });

    it('should truncate at word boundary', () => {
      const content = 'This is a test of word boundary truncation';
      const result = generateExcerpt(content, 20);
      expect(result).not.toContain('tru'); // Should not cut "truncation"
      expect(result).toContain('...');
    });

    it('should use default length if not specified', () => {
      const content = 'a'.repeat(300);
      const result = generateExcerpt(content);
      expect(result.length).toBeLessThanOrEqual(DEFAULT_EXCERPT_LENGTH + 3);
    });

    it('should strip markdown before truncating', () => {
      const content = '**Bold text** with *italic* and [links](url) that should be stripped before truncation';
      const result = generateExcerpt(content, 50);
      expect(result).not.toContain('**');
      expect(result).not.toContain('*');
      expect(result).not.toContain('[');
      expect(result).toContain('Bold text');
    });
  });

  describe('isValidExcerptLength', () => {
    it('should return true for valid length', () => {
      expect(isValidExcerptLength('Short excerpt')).toBe(true);
      expect(isValidExcerptLength('a'.repeat(500))).toBe(true);
    });

    it('should return false for invalid length', () => {
      expect(isValidExcerptLength('a'.repeat(501))).toBe(false);
    });

    it('should use custom max length', () => {
      expect(isValidExcerptLength('a'.repeat(100), 50)).toBe(false);
      expect(isValidExcerptLength('a'.repeat(50), 100)).toBe(true);
    });
  });

  describe('getExcerptPreview', () => {
    it('should return preview with metadata', () => {
      const content = 'This is test content for preview';
      const result = getExcerptPreview(content);
      
      expect(result).toHaveProperty('excerpt');
      expect(result).toHaveProperty('isAutoGenerated');
      expect(result).toHaveProperty('characterCount');
      expect(result).toHaveProperty('isTruncated');
      expect(result.isAutoGenerated).toBe(true);
      expect(result.excerpt).toBe('This is test content for preview');
      expect(result.isTruncated).toBe(false);
    });

    it('should indicate truncation', () => {
      const content = 'a'.repeat(300);
      const result = getExcerptPreview(content, 100);
      
      expect(result.isTruncated).toBe(true);
      expect(result.characterCount).toBeLessThanOrEqual(103); // 100 + '...'
    });

    it('should strip markdown in preview', () => {
      const content = '**Bold** and *italic* text';
      const result = getExcerptPreview(content);
      
      expect(result.excerpt).not.toContain('**');
      expect(result.excerpt).not.toContain('*');
      expect(result.excerpt).toContain('Bold');
    });
  });
});
