/**
 * Default Dashboard Layouts Seed
 * 
 * Creates default widget instances for each user role on dashboard pages.
 * This ensures users see a pre-configured dashboard immediately upon first visit.
 */

export const defaultLayoutsSeed = [
  // ============================================================================
  // SUPER ADMIN - Main Dashboard (/dashboard)
  // ============================================================================
  {
    userId: null, // Will be set to Super Admin user during seeding
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'system-health-card',
    position: 0,
    gridSpan: 6,
    config: { title: 'System Health' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'revenue-card',
    position: 1,
    gridSpan: 3,
    config: { title: 'Revenue' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'orders-card',
    position: 2,
    gridSpan: 3,
    config: { title: 'Orders' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'customers-card',
    position: 3,
    gridSpan: 3,
    config: { title: 'Customers' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'cron-jobs-status',
    position: 4,
    gridSpan: 6,
    config: { title: 'Cron Jobs Status', limit: 10 },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'email-delivery-stats',
    position: 5,
    gridSpan: 3,
    config: { title: 'Email Delivery' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'revenue-chart',
    position: 6,
    gridSpan: 6,
    config: { title: 'Revenue Trend', period: '30d' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'recent-orders-table',
    position: 7,
    gridSpan: 6,
    config: { title: 'Recent Orders', limit: 10 },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'security-alerts',
    position: 8,
    gridSpan: 6,
    config: { title: 'Security Alerts', limit: 5 },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'main-dashboard',
    widgetKey: 'quick-actions-grid',
    position: 9,
    gridSpan: 6,
    config: { title: 'Quick Actions' },
  },

  // ============================================================================
  // SUPER ADMIN - Analytics Dashboard (/dashboard/analytics)
  // ============================================================================
  {
    userId: null,
    role: 'Super Admin',
    page: 'analytics-dashboard',
    widgetKey: 'revenue-chart',
    position: 0,
    gridSpan: 6,
    config: { title: 'Revenue Trend', period: '30d' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'analytics-dashboard',
    widgetKey: 'sales-by-category-chart',
    position: 1,
    gridSpan: 6,
    config: { title: 'Sales by Category', period: '30d' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'analytics-dashboard',
    widgetKey: 'order-status-chart',
    position: 2,
    gridSpan: 6,
    config: { title: 'Orders by Status' },
  },
  {
    userId: null,
    role: 'Super Admin',
    page: 'analytics-dashboard',
    widgetKey: 'top-products-chart',
    position: 3,
    gridSpan: 6,
    config: { title: 'Top Selling Products', limit: 10 },
  },

  // ============================================================================
  // ADMIN - Main Dashboard (/dashboard)
  // ============================================================================
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'revenue-card',
    position: 0,
    gridSpan: 3,
    config: { title: 'Revenue' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'orders-card',
    position: 1,
    gridSpan: 3,
    config: { title: 'Orders' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'customers-card',
    position: 2,
    gridSpan: 3,
    config: { title: 'Customers' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'inventory-alerts-card',
    position: 3,
    gridSpan: 3,
    config: { title: 'Inventory Alerts' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'revenue-chart',
    position: 4,
    gridSpan: 6,
    config: { title: 'Revenue Trend', period: '30d' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'sales-by-category-chart',
    position: 5,
    gridSpan: 6,
    config: { title: 'Sales by Category', period: '30d' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'recent-orders-table',
    position: 6,
    gridSpan: 6,
    config: { title: 'Recent Orders', limit: 10 },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'low-stock-table',
    position: 7,
    gridSpan: 6,
    config: { title: 'Low Stock Products', limit: 10 },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'recent-posts-table',
    position: 8,
    gridSpan: 6,
    config: { title: 'Recent Blog Posts', limit: 10 },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'main-dashboard',
    widgetKey: 'quick-actions-grid',
    position: 9,
    gridSpan: 6,
    config: { title: 'Quick Actions' },
  },

  // ============================================================================
  // ADMIN - Analytics Dashboard (/dashboard/analytics)
  // ============================================================================
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'revenue-chart',
    position: 0,
    gridSpan: 6,
    config: { title: 'Revenue Trend', period: '30d' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'sales-by-category-chart',
    position: 1,
    gridSpan: 6,
    config: { title: 'Sales by Category', period: '30d' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'order-status-chart',
    position: 2,
    gridSpan: 6,
    config: { title: 'Orders by Status' },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'top-products-chart',
    position: 3,
    gridSpan: 6,
    config: { title: 'Top Selling Products', limit: 10 },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'recent-customers-table',
    position: 4,
    gridSpan: 6,
    config: { title: 'Recent Customers', limit: 10 },
  },
  {
    userId: null,
    role: 'Admin',
    page: 'analytics-dashboard',
    widgetKey: 'low-stock-table',
    position: 5,
    gridSpan: 6,
    config: { title: 'Low Stock Products', limit: 10 },
  },

  // ============================================================================
  // MANAGER - Main Dashboard (/dashboard)
  // ============================================================================
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'orders-card',
    position: 0,
    gridSpan: 3,
    config: { title: 'Orders' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'inventory-alerts-card',
    position: 1,
    gridSpan: 3,
    config: { title: 'Inventory Alerts' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'revenue-card',
    position: 2,
    gridSpan: 3,
    config: { title: 'Revenue' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'customers-card',
    position: 3,
    gridSpan: 3,
    config: { title: 'Customers' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'recent-orders-table',
    position: 4,
    gridSpan: 6,
    config: { title: 'Recent Orders', limit: 10 },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'low-stock-table',
    position: 5,
    gridSpan: 6,
    config: { title: 'Low Stock Products', limit: 10 },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'top-products-chart',
    position: 6,
    gridSpan: 6,
    config: { title: 'Top Selling Products', limit: 10 },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'sales-by-category-chart',
    position: 7,
    gridSpan: 6,
    config: { title: 'Sales by Category', period: '30d' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'main-dashboard',
    widgetKey: 'quick-actions-grid',
    position: 8,
    gridSpan: 12,
    config: { title: 'Quick Actions' },
  },

  // ============================================================================
  // MANAGER - Analytics Dashboard (/dashboard/analytics)
  // ============================================================================
  {
    userId: null,
    role: 'Manager',
    page: 'analytics-dashboard',
    widgetKey: 'revenue-chart',
    position: 0,
    gridSpan: 6,
    config: { title: 'Revenue Trend', period: '30d' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'analytics-dashboard',
    widgetKey: 'sales-by-category-chart',
    position: 1,
    gridSpan: 6,
    config: { title: 'Sales by Category', period: '30d' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'analytics-dashboard',
    widgetKey: 'order-status-chart',
    position: 2,
    gridSpan: 6,
    config: { title: 'Orders by Status' },
  },
  {
    userId: null,
    role: 'Manager',
    page: 'analytics-dashboard',
    widgetKey: 'top-products-chart',
    position: 3,
    gridSpan: 6,
    config: { title: 'Top Selling Products', limit: 10 },
  },

  // ============================================================================
  // USER - Main Dashboard (/dashboard)
  // ============================================================================
  {
    userId: null,
    role: 'User',
    page: 'main-dashboard',
    widgetKey: 'personal-stats-card',
    position: 0,
    gridSpan: 6,
    config: { title: 'My Stats' },
  },
  {
    userId: null,
    role: 'User',
    page: 'main-dashboard',
    widgetKey: 'profile-summary-card',
    position: 1,
    gridSpan: 6,
    config: { title: 'My Profile', showCompletion: true },
  },
  {
    userId: null,
    role: 'User',
    page: 'main-dashboard',
    widgetKey: 'notifications-feed',
    position: 2,
    gridSpan: 6,
    config: { title: 'Recent Notifications', limit: 10 },
  },
  {
    userId: null,
    role: 'User',
    page: 'main-dashboard',
    widgetKey: 'messages-feed',
    position: 3,
    gridSpan: 6,
    config: { title: 'Recent Messages', limit: 10 },
  },
  {
    userId: null,
    role: 'User',
    page: 'main-dashboard',
    widgetKey: 'quick-actions-grid',
    position: 4,
    gridSpan: 12,
    config: { title: 'Quick Actions' },
  },

  // ============================================================================
  // USER - Analytics Dashboard (/dashboard/analytics)
  // ============================================================================
  {
    userId: null,
    role: 'User',
    page: 'analytics-dashboard',
    widgetKey: 'personal-stats-card',
    position: 0,
    gridSpan: 6,
    config: { title: 'My Activity Stats' },
  },
  {
    userId: null,
    role: 'User',
    page: 'analytics-dashboard',
    widgetKey: 'notifications-feed',
    position: 1,
    gridSpan: 6,
    config: { title: 'Notification History', limit: 20 },
  },
  {
    userId: null,
    role: 'User',
    page: 'analytics-dashboard',
    widgetKey: 'messages-feed',
    position: 2,
    gridSpan: 6,
    config: { title: 'Message History', limit: 20 },
  },
];
